index.js

Set CALIBRE_HOST earlier for node api

---

.eslintignore
.eslintrc.js
.jest-setup.js
.travis.yml
__tests__/__snapshots__/index.test.js.snap
__tests__/index.test.js
index.js
jest.config.js
package-lock.json
package.json
src/cli/site/create.js

Found a bug in the last release, it looks like there is a broken path. I wanted to add unit testing too to hopefully catch other issues later. :-)
```
Cannot find module './src/api/test_profile' from 'index.js'
14 | const Snapshot = require('./src/api/snapshot')
15 | const Test = require('./src/api/test')
> 16 | const TestProfile = require('./src/api/test_profile')
17 | const Agent = require('./src/api/location')
18 |
19 | module.exports = {
```

test(index): add test showing error

---

src/cli/site/get-pulse-metrics.js

Correct CSV error

---

.gitignore
CHANGELOG.md
examples/nodejs/package.json
package-lock.json
package.json

Release 1.1.1

---

src/utils/formatters/perf-score.js

Use lighthouse number values rather than grades

---

examples/nodejs/package-lock.json
package-lock.json
package.json
src/api/test.js
src/cli/test/download-artifacts.js

Add artifact-download command

---

src/views/test.js

Display only metrics we believe in

---

package-lock.json
package.json
src/cli.js
src/utils/api-error.js

Updated yargs to handle errors better, then implemented a few enhancements that are summarised in the image above. In short:

Updated error handling 

---

.jest-setup.js
__tests__/cli/__snapshots__/index.test.js.snap
__tests__/cli/__snapshots__/site.test.js.snap
__tests__/cli/site.test.js
__tests__/cli/site/__snapshots__/delete-snapshot.test.js.snap
__tests__/cli/site/__snapshots__/snapshots.test.js.snap
__tests__/cli/site/delete-snapshot.test.js
__tests__/cli/site/snapshots.test.js
__tests__/fixtures/deleteSnapshot.json
__tests__/fixtures/listSnapshots.json
__tests__/utils.js
package-lock.json
package.json
src/cli/site/create-page.js
src/cli/site/create-snapshot.js
src/cli/site/create-test-profile.js
src/cli/site/delete-page.js
src/cli/site/delete-snapshot.js
src/cli/site/delete-test-profile.js
src/cli/site/delete.js
src/cli/site/download-snapshot-artifacts.js
src/cli/site/get-pulse-metrics.js
src/cli/site/get-snapshot-metrics.js
src/cli/site/pages.js
src/cli/site/snapshots.js
src/cli/site/test-profiles.js
src/cli/site/update-page.js
src/cli/site/update-test-profile.js
src/utils/cli.js

This PR will:
- Introduce a server which can be used for sending mock response to commands run through the `runCLI` function in tests.
- Introduce a shared options object in a cli util module to make it easier to make options consistent across commands

Integration tests

---

package-lock.json
package.json

Updates the node that gets packaged inside binary releases to node 10.

Update packaged binary node

---

.dockerignore
Dockerfile
package-lock.json
package.json
src/api/snapshot-metrics.js
src/api/test-profile.js
src/api/test.js
src/cli/site/create-test-profile.js
src/cli/site/test-profiles.js
src/cli/site/update-test-profile.js
src/cli/test/create.js
src/views/test-profile.js
src/views/test.js

**Single page tests**
Use the `--adblocker` flag to test with adblocker
**Options for updating a test profile**
* Use `--no-javascript` or `--javascript` to turn JS on/off for a profile
* Use `--no-adblocker` or `--adblocker` to turn adblocking on or off for a profile
**Listing test profiles with adblocker present**

🚧Adblocker

---

CHANGELOG.md
examples/nodejs/package.json
package.json

Release 2.0.0

---

Dockerfile
package-lock.json
package.json
script/build

The last successful build ran with pkg@4.3.7

Package with pkg@4.3.7

---

__tests__/__snapshots__/index.test.js.snap
examples/nodejs/README.md
examples/nodejs/create-integration.js
examples/nodejs/integrations/create.js
examples/nodejs/integrations/delete.js
examples/nodejs/integrations/list.js
examples/nodejs/integrations/update.js
examples/nodejs/list-integrations.js
index.js
src/api/integration.js

This PR adds integrations to the Node.JS API with examples.

Integration: Create, List, Update, Destroy

---

__tests__/__snapshots__/index.test.js.snap
examples/nodejs/README.md
examples/nodejs/agent-settings.js
index.js
src/api/agent-settings.js

This PR adds Agent Settings to the Node.JS API with an example.

Agent Settings: Update

---

__tests__/__snapshots__/index.test.js.snap
examples/nodejs/README.md
examples/nodejs/metric-budgets/create.js
examples/nodejs/metric-budgets/delete.js
examples/nodejs/metric-budgets/list.js
examples/nodejs/metric-budgets/update.js
index.js
src/api/metric-budget.js

This PR adds Metric Budgets to the Node.JS API with examples.

Metric Budgets: Create, List, Update, Destroy

---

src/api/snapshot.js

Create snapshot with optional ref

---

__tests__/cli/site/__snapshots__/get-snapshot-metrics.test.js.snap
__tests__/cli/site/get-snapshot-metrics.test.js
__tests__/fixtures/snapshotMetrics-no-snapshot.json
src/cli/site/get-snapshot-metrics.js

Return error when no snapshot found

---

examples/nodejs/sites/create.js
src/api/site.js
src/cli/site/create.js

Create site with agent settings

---

CHANGELOG.md
__tests__/cli/__snapshots__/index.test.js.snap
examples/nodejs/package.json
package-lock.json
package.json
src/cli/site/create.js

Release 3 0

---

examples/nodejs/test-profiles/create-test-profile.js
examples/nodejs/test-profiles/delete-test-profile.js
examples/nodejs/test-profiles/list-test-profiles.js
examples/nodejs/test-profiles/update-test-profiles.js

Adding the examples used in calibreapp/web#534
﻿

Added nodejs examples for managing test profiles

---

.github/workflows/codeql-analysis.yml

In this PR:
Taking this for a spin to see what it's like.

Enabling CodeQL analysis

---

src/cli/site/get-snapshot-metrics.js

This PR fixes a bug where the same profile was being returned for every metric when exporting snapshot metrics in CSV format.

Fix Snapshot CSV Export

---

src/api/deploy.js
src/api/location.js
src/api/metric-budget.js
src/api/page.js
src/api/test-profile.js

This PR will add all available fields for Test Profiles to the Node `TestProfile` API.

🔨 Add all fields for Node API queries

---

__tests__/__snapshots__/index.test.js.snap
examples/nodejs/README.md
examples/nodejs/agent-settings/get.js
examples/nodejs/sites/get.js
examples/nodejs/sites/update-authentication-settings.js
examples/nodejs/sites/update-headers-cookies.js
examples/nodejs/sites/update.js
src/api/site.js

This PR will:
- Add `Site.get`
- Add `Site.update`
- Add examples for getting a Site
- Add examples for updating a Site

✨ Add Get and Update to Site API

---

.github/workflows/test.yml

:construction_worker: Add node 17 to test harness

---

.github/workflows/test.yml
.jest-setup.js
__tests__/cli/request.test.js
jest.config.js
package.json
src/cli.js

🪟 MSFT Windows support (CAL-458)

---

.github/workflows/test.yml
.tool-versions
CHANGELOG.md
package-lock.json
package.json
src/utils/download.js

🏋️ Brotli compression

---

CLI_COMMANDS.md
__tests__/cli/site/__snapshots__/pull-request-review.test.js.snap
src/cli/site/pull-request-review.js

✨ Add markdown output to PR view command

---

CHANGELOG.md
package.json

✨ Release 5.1.2
