calibreapp/cli

- CHANGELOG.md
- package-lock.json
- package.json
- src/api/test.js
- src/cli/test/create.js
The `calibre test create <url>` command now accepts a `--cookie-jar=path/to/cookie-jar-file` flag. 
It uses the [Netscape cookie format](https://crdx.org/cookies/). Tests will be run with those cookies set.
> Add cookie jar support to `test create` command

- package.json
Following the GitHub link from your NPM page gives a 404 (and points to another user's account). This change fixes the URL.
> Fix the Git URL

- package.json
- src/cli.js
The `--no-deprecation` flag is preventing the file from executing in some cases.
> Remove --no-deprecation option

- .travis.yml
- package.json
- src/cli/site/get-snapshot-metrics.js
When outputting snapshot metrics as CSV we need to check if there's a device and/or bandwidth object.
When outputting snapshot metrics as CSV and an error is thrown we need to just return the error (same as JSON).
>  🐛 Fix get snapshot metrics csv

- examples/nodejs/get-all-pulse-metrics.js
Updated the get-all-pulse-metrics example so that uses the latest version of CLI. 
Instead of fetching all sites, then all pages, we fetch all sites, then the metrics for each site asynchronously. 
It's faster, it's smaller. 🍃
> Updated examples/nodejs/get-all-pulse-metrics.js

- __tests__/cli/__snapshots__/request.test.js.snap
- examples/nodejs/metrics-history.js
- package.json
- src/cli/request.js
Previously the following command would result in:
`calibre request --query='query GetMetricsHistory($slug: String!, $measurement: MetricTag!, $page: String!){organisation{site(slug:$slug){metricsHistory(measurement:$meas
urement, page:$page){current previous}}}}' --slug='apple' --measurement='firstRender' --page='5ee3470f-7890-4c8c-ba93-05adedfa3164'`
```
{ organisation: { site: { metricsHistory: [Array] } } }
```
Now it will result in:
```
{
"organisation": {
"site": {
"metricsHistory": [
{
"current": 282,
"previous": 370
},
{
"current": 2824,
"previous": 2985
}
]
}
}
}
```
> Log request result as JSON

- CHANGELOG.md
- __tests__/fixtures/createSiteError.json
- __tests__/utils/__snapshots__/api-error.test.js.snap
- __tests__/utils/api-error.test.js
- package.json
- src/utils/api-error.js
The Calibre GraphQL API has been updated and now returns errors in the `extensions` namespace. Errors are still returned in `problems` but this will be deprecated so this PR updates the `api-error` util to read errors from `extensions`.
>  Read errors from GraphQL extensions 

- examples/nodejs/create-test.js
- src/api/test.js
- src/cli/test/create.js
The Node.JS API uses the existing HeaderInput format of `name` and `value`.
The CLI uses key/value pairs and accepts a string or a path to a file (ala lighthouse CLI).
```
calibre test create https://www.whatsmyua.info/ --headers="[{\"User-Agent\":\"My Inline Test Agent\"}]" --location=Sydney
```
Result: https://calibreapp.com/tests/4534ee8/f1abd1a
```
calibre test create https://www.whatsmyua.info/ --headers=./headers.json --location=Sydney
```
Result: https://calibreapp.com/tests/54c32da/c743f1b
> Add headers to single page test

- CHANGELOG.md
- __tests__/cli/__snapshots__/index.test.js.snap
- examples/nodejs/time-series.js
- package.json
- src/api/time-series.js
This PR will:
- Update the TimeSeries api to return `uuid` and `canonical` for `pages` and `uuid`, `name`, `jsIsDisabled`, `adBlockIsEnabled`, `hasDeviceEmulation`, `hasBandwidthEmulation` and `isMobile` for `testProfiles`
- Add Node.JS example for fetching time series data and grouping the output by test profile
> TimeSeries: Return page and testProfile fields

- examples/nodejs/README.md
- package-lock.json
On the previous README version, the markdown link for `create-deploy.js` command was broken, due to the creation of a folder for all the new deploy commands - `create`, `delete` and `list`. 
Bearing this in mind, this fixes that broken link, as well as adds missing links for the `delete` and `list` commands.
- Update README on `examples/nodejs` to have the correct links for all the deploy command examples: `create`, `delete` and `list`
> Update nodejs examples README

- examples/nodejs/create-test.js
- src/api/test.js
- src/cli/test/create.js
This PR adds support for private single pages tests.
> Private tests

- CHANGELOG.md
- __tests__/cli/__snapshots__/index.test.js.snap
- package-lock.json
- package.json
- src/cli/site/get-pulse-metrics.js
This PR fixes a bug where to/from args were not being parsed correctly, most likely since the upgrade of date-fns.
Date parsing is now done using parseISO
> Parse to/from args with parseISO

- src/utils/token.js
The help message states to run `calibre set token`, but the command should really be `calibre token set`. 
In this PR:
> Correction: Command and options are swapped

- src/cli/site/get-pulse-metrics.js
Given that the `--page` argument is now optional, it makes sense to update the command description so that people are able to find the right command to use more easily.
> Update get pulse metrics description

- __tests__/cli/__snapshots__/index.test.js.snap
- src/cli.js
Running `calibre --help` resulted in:
> `For more information on Calibre, see undefined.`
In this PR:
> Fix help log url display

- package.json
- src/api/test-profile.js
The `javascript` flag should default to turning JavaScript on:
```
--javascript  Turn JavaScript execution on/off       [boolean] [default: true]
```
Currently, creating a new test profile disables javascript by default:
```
calibre site create-test-profile --site=calibre NewProfile
✔ Created Test Profile
⬢ NewProfile (xxx)
Created: 12:08PM 30-Sep-2020
Updated: 12:08PM 30-Sep-2020
• Javascript Disabled
```
And setting `javascript=true` disables JavaScript:
```
calibre site create-test-profile --site=calibre --javascript=true NewProfile
✔ Created Test Profile
⬢ NewProfile (78ab8d52-023a-4954-99fe-4b835af30b5e)
Created: 12:09PM 30-Sep-2020
Updated: 12:09PM 30-Sep-2020
• Javascript Disabled
```
This PR fixes this by passing the opposite of the `javascript` flag value to `jsIsDisabled` in the …
> Fix Create Test Profile: `javascript` flag

- script/publish
- script/utils/latest_version.sh
Buildkite AWS stack no longer ships with Ruby. This PR adds a bash script to get the latest version, replicating what the `latest_version.rb` ruby script was doing.
> Add bash script to get latest version

- src/api/time-series.js
This PR includes the `page` in the series response for TimeSeries so when you query multiple pages you can differentiate series by profiles and pages.
```json
{
"times": […],
"series": [
{
"name": "Profile Name",
"profile": "profile uuid",
"page": "page uuid",
"measurement": "lighthouse-performance-score",
"values": [ … ]
},
],
"pages": […]
"testProfiles": […]
"measurements": […]
"csv": ""
}
```
> TimeSeries: Return page with series data

- package-lock.json
- src/api/site.js
- src/cli/site/create.js
This PR adds the ability to set the `team` when creating a Site via the Node.JS API and CLI.
> Add `team` to Site

- src/cli/site/metrics.js
- src/utils/cli.js
Currently the `--help` output says that you can provide `--profiles` arguments to the CLI to filter the metrics to the desired Test Profiles, however that argument is not respected as it does not get passed to the GraphQL query.
This change simply passes the `profiles` command line argument through to the TimeSeries `list` call which already supports it. 
Additionally updated the CLI `options` descriptions to mark `pages` and `profiles` as array types since they accept multiple values.
Also added text to the descriptions of `pages`, `profiles` and `metrics` describing default behaviour when not set in the same form as the `from` and `to` options.
> Fix `profiles` parameter not being passed for site metrics, update CLI option descriptions

- src/cli/site/download-snapshot-artifacts.js
When the path separator appears in a profile or page name, such as a page named "Article w/ featured image," `mkdirp` will fail to create the directory, blocking snapshot downloads.
> Fix snapshot downloads when profile or page names include path separator

- CHANGELOG.md
- examples/bash/create-test.sh
- examples/nodejs/create-test.js
- examples/nodejs/sites/create.js
- examples/nodejs/test-profiles/create-test-profile.js
- package-lock.json
- package.json
- src/api/device.js
- src/cli/device-list.js
- src/cli/site/create-test-profile.js
- src/cli/site/create.js
- src/cli/site/update-test-profile.js
- src/views/test-profile.js
Prior to this PR, CLI queried Calibre's GraphQL API for `DeviceTag` enums in order to list the accepted list of devices that can be emulated. There's now a dedicated `emulatedDevices` field available in the API, so this PR updates to use that instead.
- calibreapp/app#2864
> ✨ Emulated devices API

- CHANGELOG.md
- CLI_COMMANDS.md
- __tests__/__snapshots__/index.test.js.snap
- index.js
- src/api/pull-request-review.js
- src/cli/site/create-pull-request-review.js
> 🙅‍♂️ Return Pull Request Review with failure status when budgets fail

- src/cli/test/create.js
> 🐛 Fix: `test create` report output

- CHANGELOG.md
- package.json
- src/cli/site/create-pull-request-review.js
In this PR:
† Using `--markdown` and `--waitForResult` previously resulted in a markdown string that included ANSI escape codes. This PR corrects that behavior.
> 🐛 Correct PR create command markdown output

- CHANGELOG.md
- CLI_COMMANDS.md
- generate-cli-md.js
- package-lock.json
- package.json
- src/api/test.js
- src/cli/test/create.js
- src/cli/test/list.js
> 💤 Add single page test expiration

- CHANGELOG.md
- examples/nodejs/metric-budgets/list.js
- package-lock.json
- package.json
- src/api/metric-budget.js
- src/api/site.js
- src/views/pulse-timeline.js
> 📯 Maintenance release 6.1.0
